### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [Biancakvieira/0.5.1#1]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

So faltou o destaque do link para indicar qual página está ativa. Isso poderia ser obtido com o uso de uma classe extra com efeito de negrito e então a adição dessa classe dentro do arquivo .html que a página está ativa. 

```html
<style>
  .ativo {
    text-weight: bold;
  }
</style>

<a href="pendentes.html" class="ativo pendentes">Pendentes</a>
```

**Nota:** 9 

# Comentários

Notei que muitas das suas propriedades CSS são duplicadas entre as classes `pendentes` `concluidas` e `excluidas`. Você poderia criar uma classe mais genérica para armazenar essas propriedades e então fazer uso de duas classes. Veja no exemplo abaixo que é utilizada a classe `tarefa` junto com a classe `pendentes`. 

```html
<a class="tarefa pendentes" href="/pendentes.html">Pendentes</a>
``` 

O CSS ficaria assim: 

```css
.tarefa {
    font-family: sans-serif;
    color: rgb(250, 250, 250);
    font-size: 20px;
    border-style: solid;
    text-align: center;
    border-collapse: collapse;
    border-radius: 15px;
    padding: 3px 4px 4px 4px;
    text-decoration: none;
    border: 2px solid black;
    margin: 10px;
    font-weight: bold;
}

.pendentes {
    background: #8fd14f;
}

.concluidas {
    background: #0ca789;
    
}

.excluidas {
    background: #eb4045;
}
```

Você pode imaginar agora que `tarefa` possui três subvariações: `pendentes`, `concluidas` e `excluidas`.

```mermaid
flowchart LR;
  tarefa --> concluida;
  tarefa --> pendente;
  tarefa --> excluida;
```
